@startuml funcAngerLogDelete 
title "アンガーログ削除"
participant ユーザー
participant ブラウザ
participant Next.js
participant Prisma
participant Supabase
participant PostgreSQL
participant ホーム画面

ユーザー -> ブラウザ: 怒り記録対象削除
ブラウザ -> Next.js: 怒り記録削除対象送信
Next.js -> Supabase: 怒り記録削除リクエスト
Supabase -> PostgreSQL: 怒り記録データ削除
alt 削除成功
  PostgreSQL -> Supabase: 削除成功
  Supabase -> Next.js: 削除成功
  Next.js -> ブラウザ: 削除完了メッセージ
  ブラウザ -> ホーム画面: リダイレクト
else 削除失敗
  PostgreSQL -> Supabase: 削除失敗
  Supabase -> Next.js: 削除失敗
  Next.js -> ブラウザ: エラーメッセージ
end
@enduml