@startuml funcCategoryInsert
title "作業内容の登録"

participant ユーザー
participant ブラウザ
participant Next.js
participant Prisma
participant Supabase
participant PostgreSQL
participant 作業内容一覧

ユーザー -> ブラウザ: 作業内容入力
ブラウザ -> Next.js: 作業内容送信
Next.js -> Prisma: 作業内容登録リクエスト
Prisma -> PostgreSQL: 作業内容データ挿入
alt 登録成功
PostgreSQL -> Supabase: 登録成功
  Supabase -> Next.js: 登録成功
  Next.js -> ブラウザ: 登録完了メッセージ
ブラウザ -> 作業内容一覧: リダイレクト
else 登録失敗
  PostgreSQL -> Supabase: 登録失敗
  Supabase -> Next.js: 登録失敗
  Next.js -> ブラウザ: エラーメッセージ
end

@enduml