@startuml funcCategoryUpdate
title "作業内容の更新"
participant ユーザー
participant ブラウザ
participant Next.js
participant Prisma
participant Supabase
participant PostgreSQL
participant 作業内容一覧

ユーザー -> ブラウザ: 編集内容入力
ブラウザ -> Next.js: 編集内容送信
Next.js -> Prisma: 作業内容更新リクエスト
Prisma -> PostgreSQL: 作業内容データ更新
PostgreSQL -> Prisma: 更新結果返却
Prisma -> Next.js: 更新結果返却
Next.js -> ブラウザ: 更新完了
ブラウザ -> 作業内容一覧: リダイレクト
@enduml