@startuml funcProfile
title "プロフィール変更"
participant ユーザー
participant ブラウザ
participant Next.js
participant Prisma
participant Supabase
participant PostgreSQL
participant ホーム画面

ユーザー -> ブラウザ: プロフィール変更情報入力
ブラウザ -> Next.js: プロフィール変更情報送信
Next.js -> Prisma: ユーザー情報更新リクエスト
Prisma -> PostgreSQL: ユーザー情報更新
alt 更新成功
PostgreSQL -> Supabase: 更新成功
  Supabase -> Next.js: 更新成功
  Next.js -> ブラウザ: 更新完了メッセージ
  ブラウザ -> ホーム画面: リダイレクト
else 更新失敗
  PostgreSQL -> Supabase: 更新失敗
  Supabase -> Next.js: 更新失敗
  Next.js -> ブラウザ: エラーメッセージ
end
@enduml