@startuml funcAngerLogUpdate 
title "アンガーログ編集"
participant ユーザー
participant ブラウザ
participant Next.js
participant Prisma
participant Supabase
participant PostgreSQL
participant ホーム画面

ユーザー -> ブラウザ: 怒り記録編集
ブラウザ -> Next.js: 怒り記録送信
Next.js -> Supabase: 怒り記録更新リクエスト
Supabase -> PostgreSQL: 怒り記録データ更新
alt 更新成功
PostgreSQL -> Supabase: 更新成功
  Supabase -> Next.js: 更新成功
  Next.js -> ブラウザ: 更新完了メッセージ
  ブラウザ -> ホーム画面: リダイレクト
else 更新失敗
  PostgreSQL -> Supabase: 更新失敗
  Supabase -> Next.js: 更新失敗
  Next.js -> ブラウザ: エラーメッセージ
end
@enduml