@startuml pageHomeSeaech
title "ホーム画面の表示処理"
participant 各メニュー
participant ホーム画面
participant ブラウザ
participant Next.js
participant Prisma
participant Supabase
participant PostgreSQL

各メニュー -> ホーム画面: リダイレクト
ホーム画面 -> ブラウザ: 対象日の集計要求
ブラウザ -> Next.js: 集計要求送信
Next.js -> Supabase: 集計クエリ実行
Supabase -> PostgreSQL: 集計クエリ実行
PostgreSQL -> Supabase: 集計結果返却
Supabase -> Next.js: 集計結果返却
Next.js -> Supabase: 対象日のアンガーログ情報取得クエリ実行
Supabase -> PostgreSQL: アンガーログ情報取得クエリ実行
alt 処理成功
  PostgreSQL -> Supabase: 取得成功
  Supabase -> Next.js: 取得成功
  Next.js -> ブラウザ: 集計データのグラフ情報表示
  Next.js -> ブラウザ: アンガーログ一覧情報表示
else 例外処理
  PostgreSQL -> Supabase: 取得失敗
  Supabase -> Next.js: 取得失敗
  Next.js -> ブラウザ: エラーメッセージ
end

@enduml