@startuml ScreenTrnsition
title "画面遷移図"
state ログイン
state サインアップ
state ホーム
state アンガーログ登録
state アンガーログ編集
state プロフィール
state 作業内容一覧
state 作業内容登録
state 作業内容編集
state メニュー

ログイン --> ホーム : ログイン成功
ログイン --> サインアップ : アカウント作成
サインアップ --> ホーム : サインアップ完了

ホーム --> アンガーログ編集 : アンガーログカードクリック
ホーム --> ホーム : 表示ボタンクリック
メニュー --> アンガーログ登録 : アンガーログ登録ボタンクリック
メニュー --> ホーム : ホームへボタンクリック
メニュー --> プロフィール : プロフィールアイコンクリック
メニュー --> 作業内容一覧 : 作業一覧アイコンクリック
メニュー --> ログイン : ログアウト

アンガーログ編集 --> ホーム : 編集・削除完了
アンガーログ登録 --> ホーム : 登録完了
プロフィール --> ホーム : 保存完了
作業内容一覧 --> 作業内容登録 : 新規作成ボタンクリック
作業内容一覧 --> 作業内容編集 : 編集ボタンクリック
作業内容登録 --> 作業内容一覧 : 登録完了
作業内容編集 --> 作業内容一覧 : 更新完了
作業内容一覧 --> ホーム : 戻るボタンクリック

@enduml